---
- name: Install preload
  dnf:
    name: 
      - google-chrome-stable
    state: latest
    

- name: Uninstall gnome-keyring
  ansible.builtin.dnf:
    name: gnome-keyring
    state: absent
    autoremove: yes    