- name: Enable the RPM Fusion repository
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present

- name: Install fedora-workstation-repositories
  dnf:
    name:
      - fedora-workstation-repositories
    state: latest

    