---
- name: Enable the RPM Fusion repository
  shell: "sudo dnf -y install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"
  
- name: Install fedora-workstation-repositories
  dnf:
    name:
      - fedora-workstation-repositories
    state: latest
